### ISSUE TITLE
Proposal to modify code in updateStaliro file

### ISSUE THREAD

**Issue by michaelmarzella** [Hecate-SBST/Hecate#2]
Propose a modification to the updateStaliro file to improve cross-platform compability. Specifically, i made the following changes:

-Added an if condition to determine the Operating System (lines 28-33)

-Adapted the code accordingly (lines 38-39, 47-48 and 59-60)

https://gist.github.com/michaelmarzella/ca7f75cccae3b94695a1663a9515a1f1

**Comment by FedFormi** [comment]
Dear @michaelmarzella,
thanks for bringing this issue to my attention.

I just pushed a fix for it in the main repo. I decided to use the native Matlab variable `filesep` instead of your solution because it's standard practice, but I'm sure your proposed solution would have worked the same.
[MathWorks documentation on filesep](https://www.mathworks.com/help/matlab/ref/filesep.html)

Please let me know if this fix solves the issue on your machine.

FedFormi
